version: '3.7'

services:

  rs1:
    container_name: rs1
    image: mongo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    command: mongod --replSet replica-set
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  rs2:
    container_name: rs2
    image: mongo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    command: mongod --replSet replica-set
    ports:
      - "27018:27017"
    networks:
      - mongo-network

  rs3:
    container_name: rs3
    image: mongo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    command: mongod --replSet replica-set
    ports:
      - "27019:27017"
    networks:
      - mongo-network
    
  # simply container to startup the replica set
  mongo-startup:
    container_name: mongo-startup
    image: mongo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      - rs1
      - rs2
      - rs3
    command: >
      mongosh --host rs1:27017 --eval 'db=(new Mongo("rs1:27017")).getDB("local"); 
        config = {
          "_id" : "replica-set",
          "members" : [
            {"_id" : 0,"host" : "rs1:27017"},
            {"_id" : 1,"host" : "rs2:27017"},
            {"_id" : 2,"host" : "rs3:27017"}
          ] 
        };
        rs.initiate(config);'
    networks:
      - mongo-network

networks: 
    mongo-network:
      driver: bridge