import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Header from './components/header/header'

import './globals.css'

const inter = Roboto({ weight: ['100', '400', '900'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cadê meu time',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
